### ISSUE TITLE
Support Human Resources Machine archives

### ISSUE THREAD

**Issue by darkf** [meh2481/liTools#1]
Seems to use the same engine. `strip` can extract `resource.pak`, but you get a bunch of `No residmap entry for id ...` when trying to decompress it.

(Funny enough I was REing the .pak format for fun, but it seems I no longer have to since this tool exists. Darn. :) I guess I will have to figure out what residmaps are now. Any clues?)

**Comment by Mygod** [comment]
residmaps are a reverse lookup (from hash code to path) that's hardcoded into this tool. You can go to infernofans.com where tomorrow corporation has given a lot of detailed information in one of the forum topics.

**Comment by darkf** [comment]
@Mygod Thanks for the information, checking out that thread now. :)

HRM only appears to have one .pak at 20480, and it doesn't seem to contain b7e44207 (`vdata/residmap.dat`). Looking through the .exe's strings I only see references to animmanifest, effectmanifest, fontmanifest, langlist.bin, sndmanifest, and texmanifest.bin. Perhaps they did away with it, or it lives under another name?

**Comment by meh2481** [comment]
I'm currently in contact with Allan to get a similar residmap.dat file for for HRM. I've yet to find a good way to distinguish file types otherwise. He says a couple of things in the format changed, as well.

**Comment by darkf** [comment]
@meh2481 Any progress on this? Do you have any documentation yet?

**Comment by meh2481** [comment]
Yes, and I have images decompressing properly now. I'm debating splitting HRM off into a separate branch or repo, however, because there are a lot of format differences, with no version number differences or similar method to distinguish the files.

**Comment by darkf** [comment]
@meh2481 Yeah, I'd suggest another repo. Mind sharing the docs/code? :)

**Comment by darkf** [comment]
@meh2481 Well, any progress on the new repository / docs? Would love to start modding this game if possible.

**Comment by meh2481** [comment]
See https://github.com/meh2481/hrmTools
